ersion: "3.1"
networks:
 appone:
   external: true
services:
 mongo1:
   deploy:
     replicas: 1
     update_config:
       parallelism: 1
       delay: 10s
       failure_action: rollback
     placement:
       constraints:
         - "node.role == manager"
   hostname: mongo1
   container_name: localmongo1
   image: mongo:4.1
   dns:
     - 127.0.0.11
     - 8.8.8.8
   networks:
     always_private:
       aliases:
         - mongo.alwayshired.com
   volumes:
     - /data/mongo:/data/db
   ports:
     - 27017:27017
   logging:
     driver: syslog
     options:
         syslog-facility: "local6"
         syslog-address: "tcp://127.0.0.1:602"
         tag: "docker-{{.Name}}/{{.ID}}"
   restart: always
   entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--auth" ]
