module.exports = {
  REDIS_URI: process.env.REDIS_URI,
  CRON_EXPRESSION_HUBSPOT_PULL: process.env.CRON_EXPRESSION_HUBSPOT_PULL,
  CRON_EXPRESSION_APPONE_PULL: process.env.CRON_EXPRESSION_APPONE_PULL,
  APPONE_USERNAME: process.env.APPONE_USERNAME,
  APPONE_PASSWORD: process.env.APPONE_PASSWORD,
  APPONE_DEALERID: process.env.APPONE_DEALERID,
  APPONE_POLL_DEALERIDS: process.env.APPONE_POLL_DEALERIDS,
  APPONE_URL: process.env.APPONE_URL,
  APPONE_API_KEY: process.env.APPONE_API_KEY,
  APPONE_BASIC_USERNAME: process.env.APPONE_BASIC_USERNAME,
  APPONE_BASIC_PASSWORD: process.env.APPONE_BASIC_PASSWORD,
};
